"""test

Revision ID: 2b75025afbc6
Revises: 71fe42b9d016
Create Date: 2023-01-09 17:44:03.215592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b75025afbc6'
down_revision = '71fe42b9d016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events__signs_id', table_name='events__signs')
    op.drop_column('events__signs', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events__signs', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_events__signs_id', 'events__signs', ['id'], unique=False)
    # ### end Alembic commands ###
