"""Update events

Revision ID: 32b1d06a4f86
Revises: 6492c15234b7
Create Date: 2023-01-05 16:28:18.492605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b1d06a4f86'
down_revision = '6492c15234b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('events', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['updated_by'], ['id'])
    op.add_column('events__characteristics', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events__characteristics', 'events', ['event_id'], ['id'])
    op.add_column('events__contacts', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events__contacts', 'events', ['event_id'], ['id'])
    op.add_column('events__links', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events__links', 'events', ['event_id'], ['id'])
    op.add_column('events__qa', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events__qa', 'events', ['event_id'], ['id'])
    op.add_column('events_date', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events_date', 'events', ['event_id'], ['id'])
    op.add_column('users__links', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users__links', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users__links', 'users', ['user_id'], ['id'])
    op.drop_column('users__links', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users__links', sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users__links', type_='foreignkey')
    op.drop_column('users__links', 'user_id')
    op.drop_column('users__links', 'name')
    op.drop_constraint(None, 'events_date', type_='foreignkey')
    op.drop_column('events_date', 'event_id')
    op.drop_constraint(None, 'events__qa', type_='foreignkey')
    op.drop_column('events__qa', 'event_id')
    op.drop_constraint(None, 'events__links', type_='foreignkey')
    op.drop_column('events__links', 'event_id')
    op.drop_constraint(None, 'events__contacts', type_='foreignkey')
    op.drop_column('events__contacts', 'event_id')
    op.drop_constraint(None, 'events__characteristics', type_='foreignkey')
    op.drop_column('events__characteristics', 'event_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'updated_by')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_by')
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###
