"""Add events

Revision ID: 6492c15234b7
Revises: af2a09c5e248
Create Date: 2023-01-05 15:57:02.954786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6492c15234b7'
down_revision = 'af2a09c5e248'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('repeatable', sa.Boolean(), nullable=True),
    sa.Column('repeatable_type', sa.String(length=255), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('is_announcement', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('events__characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events__characteristics_id'), 'events__characteristics', ['id'], unique=False)
    op.create_table('events__contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events__contacts_id'), 'events__contacts', ['id'], unique=False)
    op.create_table('events__links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events__links_id'), 'events__links', ['id'], unique=False)
    op.create_table('events__qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events__qa_id'), 'events__qa', ['id'], unique=False)
    op.create_table('events_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_date_id'), 'events_date', ['id'], unique=False)
    op.create_table('users__links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users__links_id'), 'users__links', ['id'], unique=False)
    op.create_table('events_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_signs_id'), 'events_signs', ['id'], unique=False)
    op.add_column('users', sa.Column('phone', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone')
    op.drop_index(op.f('ix_events_signs_id'), table_name='events_signs')
    op.drop_table('events_signs')
    op.drop_index(op.f('ix_users__links_id'), table_name='users__links')
    op.drop_table('users__links')
    op.drop_index(op.f('ix_events_date_id'), table_name='events_date')
    op.drop_table('events_date')
    op.drop_index(op.f('ix_events__qa_id'), table_name='events__qa')
    op.drop_table('events__qa')
    op.drop_index(op.f('ix_events__links_id'), table_name='events__links')
    op.drop_table('events__links')
    op.drop_index(op.f('ix_events__contacts_id'), table_name='events__contacts')
    op.drop_table('events__contacts')
    op.drop_index(op.f('ix_events__characteristics_id'), table_name='events__characteristics')
    op.drop_table('events__characteristics')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
