"""Edit users

Revision ID: 6535d1d71f02
Revises: ab535303de5d
Create Date: 2022-12-29 12:54:57.048175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6535d1d71f02'
down_revision = 'ab535303de5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
