"""Edit users

Revision ID: 6672c44e9415
Revises: 6535d1d71f02
Create Date: 2022-12-29 12:58:29.212490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6672c44e9415'
down_revision = '6535d1d71f02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
