"""add categories and tags

Revision ID: 71fe42b9d016
Revises: 32b1d06a4f86
Create Date: 2023-01-05 21:36:35.754439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71fe42b9d016'
down_revision = '32b1d06a4f86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('events__date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events__date_id'), 'events__date', ['id'], unique=False)
    op.create_table('events__signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events__signs_id'), 'events__signs', ['id'], unique=False)
    op.create_table('events__tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events__tags_id'), 'events__tags', ['id'], unique=False)
    op.drop_index('ix_events_signs_id', table_name='events_signs')
    op.drop_table('events_signs')
    op.drop_index('ix_events_date_id', table_name='events_date')
    op.drop_table('events_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_date',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='events_date_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='events_date_pkey')
    )
    op.create_index('ix_events_date_id', 'events_date', ['id'], unique=False)
    op.create_table('events_signs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='events_signs_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='events_signs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='events_signs_pkey')
    )
    op.create_index('ix_events_signs_id', 'events_signs', ['id'], unique=False)
    op.drop_index(op.f('ix_events__tags_id'), table_name='events__tags')
    op.drop_table('events__tags')
    op.drop_index(op.f('ix_events__signs_id'), table_name='events__signs')
    op.drop_table('events__signs')
    op.drop_index(op.f('ix_events__date_id'), table_name='events__date')
    op.drop_table('events__date')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
